import type { Hotel } from "@/api/getHotels";

// Placeholder data shown until the `/api/hotels` endpoint goes live. Mirrors the
// reference design so the page is fully functional in the meantime.
export const hotelsFallback: Hotel[] = [
  {
    id: 1,
    name_en: "Yupek Yoly Hotel",
    name_ru: "Отель Юпек Йолы",
    name_tk: "Ýüpek Ýoly myhmanhanasy",
    city_en: "Mary",
    city_ru: "Мары",
    city_tk: "Mary",
    address_en: "Gowshuthan Kochesi, Mary, Turkmenistan",
    address_ru: "Говшутхан кочеси, Мары, Туркменистан",
    address_tk: "Gowşuthan köçesi, Mary, Türkmenistan",
    image: "",
    rating: 4,
    reviews: 2,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 2,
    name_en: "Dashoguz Hotel",
    name_ru: "Отель Дашогуз",
    name_tk: "Daşoguz myhmanhanasy",
    city_en: "Dashoguz",
    city_ru: "Дашогуз",
    city_tk: "Daşoguz",
    address_en: "Ruhnama 100, Dashoguz",
    address_ru: "Рухнама 100, Дашогуз",
    address_tk: "Ruhnama 100, Daşoguz",
    image: "",
    rating: 4,
    reviews: 32,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 3,
    name_en: "Uzboy Hotel",
    name_ru: "Отель Узбой",
    name_tk: "Uzboý myhmanhanasy",
    city_en: "Dashoguz",
    city_ru: "Дашогуз",
    city_tk: "Daşoguz",
    address_en: "19/1, Turkmenbashi street, Dashoguz, Turkmenistan",
    address_ru: "19/1, улица Туркменбаши, Дашогуз, Туркменистан",
    address_tk: "19/1, Türkmenbaşy köçesi, Daşoguz, Türkmenistan",
    image: "",
    rating: 3,
    reviews: 16,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
];
