import type { Hotel } from "@/api/getHotels";

// Placeholder data shown until the `/api/hotels` endpoint goes live. Mirrors the
// reference design so the page is fully functional in the meantime.
export const hotelsFallback: Hotel[] = [
  {
    id: 1,
    country: "turkmenistan",
    name_en: "Yyldyz Hotel",
    name_ru: "Отель «Йылдыз»",
    name_tk: "Ýyldyz myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "2002/5 (Bagtyýarlyk), 17, Ashgabat",
    address_ru: "2002/5 (Багтыярлык), 17, Ашхабад",
    address_tk: "2002/5 (Bagtyýarlyk), 17, Aşgabat",
    image: "/Hotels/yyldyz.jpeg",
    rating: 4.5,
    reviews: 194,
    review_label_en: "Excellent",
    review_label_ru: "Отлично",
    review_label_tk: "Ajaýyp",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 2,
    country: "turkmenistan",
    name_en: "Oguzkent Hotel",
    name_ru: "Отель «Огузкент»",
    name_tk: "Oguzkent myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "231, Av. Bitarap, Ashgabat",
    address_ru: "231, пр. Битарап, Ашхабад",
    address_tk: "231, Bitarap şaýoly, Aşgabat",
    image: "/Hotels/oguzkent.jpg",
    rating: 5,
    reviews: 232,
    review_label_en: "Excellent",
    review_label_ru: "Отлично",
    review_label_tk: "Ajaýyp",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 3,
    country: "turkmenistan",
    name_en: "Archabil Hotel",
    name_ru: "Отель «Арчабиль»",
    name_tk: "Arçabil myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "54, Av. Archabil, Ashgabat",
    address_ru: "54, пр. Арчабиль, Ашхабад",
    address_tk: "54, Arçabil şaýoly, Aşgabat",
    image: "/Hotels/archabil.jpeg",
    rating: 5,
    reviews: 83,
    review_label_en: "Excellent",
    review_label_ru: "Отлично",
    review_label_tk: "Ajaýyp",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 4,
    country: "turkmenistan",
    name_en: "Olimpia Hotel",
    name_ru: "Отель «Олимпия»",
    name_tk: "Olimpiýa myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "4, Av. Saparmyrat Turkmenbashy, Ashgabat",
    address_ru: "4, пр. Сапармурат Туркменбаши, Ашхабад",
    address_tk: "4, Saparmyrat Türkmenbaşy şaýoly, Aşgabat",
    image: "/Hotels/olimpia.jpeg",
    rating: 5,
    reviews: 8,
    review_label_en: "Excellent",
    review_label_ru: "Отлично",
    review_label_tk: "Ajaýyp",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 5,
    country: "turkmenistan",
    name_en: "Sport Hotel",
    name_ru: "Спорт-отель",
    name_tk: "Sport myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "Olimpic complex, Av. 10 yyl Abadanchylyk, Ashgabat",
    address_ru: "Олимпийский комплекс, пр. 10 ýyl Abadançylyk, Ашхабад",
    address_tk: "Olimpiýa toplumy, 10 ýyl Abadançylyk şaýoly, Aşgabat",
    image: "/Hotels/sport.jpg",
    rating: 4,
    reviews: 6,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 6,
    country: "turkmenistan",
    name_en: "Grand Turkmen Hotel",
    name_ru: "Гранд-отель «Туркмен»",
    name_tk: "Grand Türkmen myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "7, Gorogly str., Ashgabat",
    address_ru: "7, ул. Гёроглы, Ашхабад",
    address_tk: "7, Görogly köçesi, Aşgabat",
    image: "/Hotels/grand.jpg",
    rating: 4,
    reviews: 0,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 7,
    country: "turkmenistan",
    name_en: "Ak Altyn Hotel",
    name_ru: "Отель «Ак Алтын»",
    name_tk: "Ak Altyn myhmanhanasy",
    city_en: "Ashgabat",
    city_ru: "Ашхабад",
    city_tk: "Aşgabat",
    address_en: "Magtymguly Av, 144/1, Ashgabat",
    address_ru: "пр. Махтумкули, 144/1, Ашхабад",
    address_tk: "Magtymguly şaýoly, 144/1, Aşgabat",
    image: "/Hotels/akAltyn.jpg",
    rating: 4,
    reviews: 196,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 8,
    country: "turkmenistan",
    name_en: "Mary Hotel",
    name_ru: "Отель «Мары»",
    name_tk: "Mary myhmanhanasy",
    city_en: "Mary",
    city_ru: "Мары",
    city_tk: "Mary",
    address_en: "Mary, Turkmenistan",
    address_ru: "Мары, Туркменистан",
    address_tk: "Mary, Türkmenistan",
    image: "/Hotels/mary.jpeg",
    rating: 4,
    reviews: 91,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 9,
    country: "turkmenistan",
    name_en: "Margush Hotel",
    name_ru: "Отель «Маргуш»",
    name_tk: "Marguş myhmanhanasy",
    city_en: "Mary",
    city_ru: "Мары",
    city_tk: "Mary",
    address_en: "Gowshuthan Kochesi, Mary, Turkmenistan",
    address_ru: "Говшутхан кочеси, Мары, Туркменистан",
    address_tk: "Gowşuthan köçesi, Mary, Türkmenistan",
    image: "/Hotels/margush.jpg",
    rating: 3,
    reviews: 50,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 10,
    country: "turkmenistan",
    name_en: "Yupek Yoly Hotel",
    name_ru: "Отель «Юпек Йолы»",
    name_tk: "Ýüpek Ýoly myhmanhanasy",
    city_en: "Mary",
    city_ru: "Мары",
    city_tk: "Mary",
    address_en: "Gowshuthan Kochesi, Mary, Turkmenistan",
    address_ru: "Говшутхан кочеси, Мары, Туркменистан",
    address_tk: "Gowşuthan köçesi, Mary, Türkmenistan",
    image: "/Hotels/yupek.webp",
    rating: 4,
    reviews: 2,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 11,
    country: "turkmenistan",
    name_en: "Dashoguz Hotel",
    name_ru: "Отель «Дашогуз»",
    name_tk: "Daşoguz myhmanhanasy",
    city_en: "Dashoguz",
    city_ru: "Дашогуз",
    city_tk: "Daşoguz",
    address_en: "Ruhnama 100, Dashoguz",
    address_ru: "Рухнама 100, Дашогуз",
    address_tk: "Ruhnama 100, Daşoguz",
    image: "/Hotels/hotel-dashoguz.jpg",
    rating: 4,
    reviews: 32,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
  {
    id: 12,
    country: "turkmenistan",
    name_en: "Uzboy Hotel",
    name_ru: "Отель «Узбой»",
    name_tk: "Uzboý myhmanhanasy",
    city_en: "Dashoguz",
    city_ru: "Дашогуз",
    city_tk: "Daşoguz",
    address_en: "19/1, Turkmenbashi street, Dashoguz, Turkmenistan",
    address_ru: "19/1, улица Туркменбаши, Дашогуз, Туркменистан",
    address_tk: "19/1, Türkmenbaşy köçesi, Daşoguz, Türkmenistan",
    image: "/Hotels/uzboy.jpg",
    rating: 3,
    reviews: 16,
    review_label_en: "Good",
    review_label_ru: "Хорошо",
    review_label_tk: "Gowy",
    breakfast: 1,
    kids_play_area: 1,
    parking: 1,
    wifi: 1,
    included_breakfast: 1,
    included_travel_tax: 1,
    book_url: "#",
  },
];
