import type { Metadata } from "next";
import "./globals.css";
import Header from "../../Components/Header/Header";
import Footer from "../../Components/Footer/Footer";
import Providers from "../Redux/Provider";
import BodyWrapper from "../Redux/BodyProvider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <Providers>
        <NextIntlClientProvider>
          <BodyWrapper>
            <Header />
            {children}
            <Footer />
          </BodyWrapper>
        </NextIntlClientProvider>
      </Providers>
    </html>
  );
}
